In [ ]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from tqdm import tqdm
import re
import ast

In [ ]:
url = 'https://www.timeanddate.com/scripts/cityajax.php?n=usa/new-york&mode=historic&hd=20260202&month=2&year=2026&json=1'

page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')
text = soup.get_text()
text = text.replace('&lt;', '<').replace('&gt;', '>').replace('&quot;', '"')

json_like = re.search(r'\[\{.*\}\]', text)
if json_like:
    cleaned_json = json_like.group(0)
    cleaned_json = cleaned_json.replace('\"', '"').replace('\\/', '/')
    print(cleaned_json[:500])

[{c:[{h:"00:51Mon, 2 Feb</span>"},{s:"wt-ic",h:""},{h:"-9 °C"},{s:"small",h:"Clear."},{s:"sep",h:"13 km/h"},{h:"↑</span>"},{h:"56%"},{s:"sep",h:"1013 mbar"},{h:"16 km"}]},{c:[{h:"01:51"},{s:"wt-ic",h:""},{h:"-9 °C"},{s:"small",h:"Clear."},{s:"sep",h:"13 km/h"},{h:"↑</span>"},{h:"51%"},{s:"sep",h:"1014 mbar"},{h:"16 km"}]},{c:[{h:"02:51"},{s:"wt-ic",h:""},{h:"-9 °C"},{s:"small",h:"Clear."},{s:"sep",h:"11 km/h"},{h:"↑</span>"},{h:"46%"},{s:"sep",h:"1014 mbar"},{h:"16 km"}]},{c:[{h:"03:51"},{s:"wt-

In [ ]:

text = text.replace('&lt;', '<').replace('&gt;', '>').replace('&quot;', '"').replace('\\', '')
blocks = re.findall(r'\{c:\[(.*?)\]\}', text, re.DOTALL)

rows = []
for block in blocks:
    cells = re.findall(r'h:"(.*?)"', block, re.DOTALL)
    cells = [re.sub(r'<.*?>', '', c).strip() for c in cells]
    while len(cells) < 9:
        cells.append(None)
    rows.append(cells)

columns = ['Time', 'Icon', 'Temperature', 'Condition', 'Wind', 'Wind Direction', 'Humidity', 'Pressure', 'Visibility']
df = pd.DataFrame(rows, columns=columns)
df

,Time,Icon,Temperature,Condition,Wind,Wind Direction,Humidity,Pressure,Visibility
0,"00:51Mon, 2 Feb",,-9 °C,Clear.,13 km/h,↑,56%,1013 mbar,16 km
1,01:51,,-9 °C,Clear.,13 km/h,↑,51%,1014 mbar,16 km
2,02:51,,-9 °C,Clear.,11 km/h,↑,46%,1014 mbar,16 km
3,03:51,,-9 °C,Clear.,7 km/h,↑,45%,1014 mbar,16 km
4,04:51,,-9 °C,Clear.,17 km/h,↑,47%,1014 mbar,16 km
5,05:51,,-9 °C,Clear.,17 km/h,↑,49%,1015 mbar,16 km
6,06:51,,-8 °C,Clear.,9 km/h,↑,47%,1015 mbar,16 km
7,07:51,,-8 °C,Sunny.,15 km/h,↑,49%,1016 mbar,16 km
8,08:51,,-7 °C,Sunny.,17 km/h,↑,45%,1016 mbar,16 km
9,09:51,,-5 °C,Sunny.,N/A,↑,42%,1016 mbar,16 km
10,10:51,,-3 °C,Sunny.,20 km/h,↑,42%,1016 mbar,16 km
11,11:51,,-2 °C,Sunny.,20 km/h,↑,41%,1016 mbar,16 km
12,12:51,,-1 °C,Sunny.,20 km/h,↑,36%,1015 mbar,16 km
13,13:51,,1 °C,Sunny.,13 km/h,↑,35%,1015 mbar,16 km
14,14:51,,1 °C,Sunny.,13 km/h,↑,34%,1015 mbar,16 km
15,15:51,,2 °C,Sunny.,13 km/h,↑,31%,1016 mbar,16 km
16,16:51,,1 °C,Sunny.,9 km/h,↑,35%,1016 mbar,16 km
17,17:51,,0 °C,Clear.,11 km/h,↑,38%,1017 mbar,16 km
18,18:51,,-1 °C,Clear.,N/A,↑,41%,1018 mbar,16 km
19,19:51,,-2 °C,Clear.,9 km/h,↑,45%,1018 mbar,16 km
20,20:51,,-2 °C,Clear.,15 km/h,↑,43%,1019 mbar,16 km
21,21:51,,-2 °C,Clear.,13 km/h,↑,45%,1019 mbar,16 km
22,22:51,,-3 °C,Clear.,7 km/h,↑,46%,1019 mbar,16 km
23,23:51,,-3 °C,Clear.,9 km/h,↑,45%,1019 mbar,16 km

In [25]:
df_final= pd.DataFrame()
for month in tqdm(range(1, 13)):
    for day in tqdm(range(1, 32)):
        try:
            url = f'https://www.timeanddate.com/scripts/cityajax.php?n=usa/new-york&mode=historic&hd=2024{month:02d}{day:02d}&month={month:02d}&year=2024&json=1'

            page = requests.get(url)
            page.raise_for_status()

            soup = BeautifulSoup(page.text, 'html.parser')
            text = soup.get_text()
            text = text.replace('&lt;', '<').replace('&gt;', '>').replace('&quot;', '"')
            if "No data available for the given date" in soup.get_text():
                print(f"⚠️ No data available for {month}-{day}. Skipping.")
                continue

            json_like = re.search(r'\[\{.*\}\]', text)
            if json_like:
                cleaned_json = json_like.group(0)
                cleaned_json = cleaned_json.replace('\"', '"').replace('\\/', '/')

            text = text.replace('&lt;', '<').replace('&gt;', '>').replace('&quot;', '"').replace('\\', '')
            blocks = re.findall(r'\{c:\[(.*?)\]\}', text, re.DOTALL)

            rows = []
            for block in blocks:
                cells = re.findall(r'h:"(.*?)"', block, re.DOTALL)
                cells = [re.sub(r'<.*?>', '', c).strip() for c in cells]
                while len(cells) < 9:
                    cells.append(None)
                rows.append(cells)

            columns = ['Time', 'Icon', 'Temperature', 'Condition', 'Wind', 'Wind Direction', 'Humidity', 'Pressure', 'Visibility']
            df = pd.DataFrame(rows, columns=columns)
            df["day"] = day
            df["month"] = month
            df_final = pd.concat([df_final, df], ignore_index=True)
        except requests.exceptions.RequestException as e:
                  print(f"❌ Request failed for {month}-{day}: {e}")
                  continue
        except Exception as e:
                  print(f"❌ Unexpected error on {month}-{day}: {e}")
                  continue

  0%|          | 0/12 [00:00<?, ?it/s]
  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:06,  4.92it/s]
  6%|▋         | 2/31 [00:00<00:05,  4.95it/s]
 10%|▉         | 3/31 [00:00<00:05,  4.98it/s]
 13%|█▎        | 4/31 [00:00<00:05,  4.87it/s]
 16%|█▌        | 5/31 [00:01<00:05,  4.86it/s]
 19%|█▉        | 6/31 [00:01<00:05,  4.92it/s]
 23%|██▎       | 7/31 [00:01<00:04,  4.87it/s]
 26%|██▌       | 8/31 [00:01<00:05,  3.88it/s]
 29%|██▉       | 9/31 [00:02<00:05,  4.13it/s]
 32%|███▏      | 10/31 [00:02<00:04,  4.28it/s]
 35%|███▌      | 11/31 [00:02<00:04,  4.49it/s]
 39%|███▊      | 12/31 [00:02<00:05,  3.79it/s]
 42%|████▏     | 13/31 [00:02<00:04,  4.04it/s]
 45%|████▌     | 14/31 [00:03<00:03,  4.29it/s]
 48%|████▊     | 15/31 [00:03<00:03,  4.46it/s]
 52%|█████▏    | 16/31 [00:03<00:03,  4.57it/s]
 55%|█████▍    | 17/31 [00:03<00:02,  4.75it/s]
 58%|█████▊    | 18/31 [00:03<00:02,  4.80it/s]
 61%|██████▏   | 19/31 [00:04<00:02,  4.94it/s]
 65%|██████▍   | 20/31 [00:04<00:02,  4.90it/s]
 68%|██████▊   | 21/31 [00:04<00:01,  5.41it/s]
 71%|███████   | 22/31 [00:04<00:01,  5.27it/s]
 74%|███████▍  | 23/31 [00:05<00:01,  4.10it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  4.30it/s]
 81%|████████  | 25/31 [00:05<00:01,  3.67it/s]
 84%|████████▍ | 26/31 [00:05<00:01,  3.98it/s]
 87%|████████▋ | 27/31 [00:06<00:00,  4.20it/s]
 90%|█████████ | 28/31 [00:06<00:00,  4.72it/s]
 94%|█████████▎| 29/31 [00:06<00:00,  4.68it/s]
 97%|█████████▋| 30/31 [00:06<00:00,  4.32it/s]
100%|██████████| 31/31 [00:06<00:00,  4.48it/s]
  8%|▊         | 1/12 [00:06<01:16,  6.93s/it]
  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:11,  2.68it/s]
  6%|▋         | 2/31 [00:00<00:10,  2.70it/s]
 10%|▉         | 3/31 [00:00<00:08,  3.39it/s]
 13%|█▎        | 4/31 [00:01<00:06,  3.89it/s]
 16%|█▌        | 5/31 [00:01<00:06,  4.28it/s]
 19%|█▉        | 6/31 [00:01<00:05,  4.53it/s]
 23%|██▎       | 7/31 [00:01<00:07,  3.36it/s]
 26%|██▌       | 8/31 [00:02<00:06,  3.79it/s]
 29%|██▉       | 9/31 [00:02<00:05,  4.06it/s]
 32%|███▏      | 10/31 [00:02<00:04,  4.24it/s]
 35%|███▌      | 11/31 [00:02<00:05,  3.52it/s]
 39%|███▊      | 12/31 [00:03<00:04,  3.94it/s]
 42%|████▏     | 13/31 [00:03<00:05,  3.47it/s]
 45%|████▌     | 14/31 [00:03<00:04,  4.12it/s]
 48%|████▊     | 15/31 [00:03<00:03,  4.23it/s]
 52%|█████▏    | 16/31 [00:04<00:04,  3.61it/s]
 55%|█████▍    | 17/31 [00:04<00:04,  3.30it/s]
 58%|█████▊    | 18/31 [00:05<00:04,  3.07it/s]
 61%|██████▏   | 19/31 [00:05<00:04,  2.73it/s]
 65%|██████▍   | 20/31 [00:05<00:03,  3.19it/s]
 68%|██████▊   | 21/31 [00:05<00:02,  3.55it/s]
 71%|███████   | 22/31 [00:06<00:02,  3.94it/s]
 74%|███████▍  | 23/31 [00:06<00:01,  4.18it/s]
 77%|███████▋  | 24/31 [00:06<00:01,  4.42it/s]
 81%|████████  | 25/31 [00:06<00:01,  4.38it/s]
 84%|████████▍ | 26/31 [00:06<00:01,  4.32it/s]
 87%|████████▋ | 27/31 [00:07<00:00,  4.24it/s]
 90%|█████████ | 28/31 [00:07<00:00,  4.35it/s]
 94%|█████████▎| 29/31 [00:07<00:00,  4.50it/s]
 97%|█████████▋| 30/31 [00:07<00:00,  4.65it/s]

⚠️ No data available for 2-30. Skipping.

100%|██████████| 31/31 [00:08<00:00,  3.86it/s]
 17%|█▋        | 2/12 [00:14<01:15,  7.58s/it]

⚠️ No data available for 2-31. Skipping.

  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:05,  5.13it/s]
  6%|▋         | 2/31 [00:00<00:05,  5.02it/s]
 10%|▉         | 3/31 [00:00<00:05,  5.06it/s]
 13%|█▎        | 4/31 [00:00<00:05,  4.88it/s]
 16%|█▌        | 5/31 [00:01<00:05,  4.91it/s]
 19%|█▉        | 6/31 [00:01<00:06,  3.79it/s]
 23%|██▎       | 7/31 [00:01<00:06,  3.85it/s]
 26%|██▌       | 8/31 [00:01<00:05,  4.00it/s]
 29%|██▉       | 9/31 [00:02<00:05,  3.94it/s]
 32%|███▏      | 10/31 [00:02<00:05,  4.04it/s]
 35%|███▌      | 11/31 [00:02<00:04,  4.20it/s]
 39%|███▊      | 12/31 [00:02<00:04,  4.42it/s]
 42%|████▏     | 13/31 [00:03<00:04,  3.75it/s]
 45%|████▌     | 14/31 [00:03<00:04,  4.06it/s]
 48%|████▊     | 15/31 [00:03<00:03,  4.27it/s]
 52%|█████▏    | 16/31 [00:03<00:03,  4.47it/s]
 55%|█████▍    | 17/31 [00:03<00:03,  4.61it/s]
 58%|█████▊    | 18/31 [00:04<00:02,  4.51it/s]
 61%|██████▏   | 19/31 [00:04<00:03,  3.68it/s]
 65%|██████▍   | 20/31 [00:04<00:02,  4.00it/s]
 68%|██████▊   | 21/31 [00:04<00:02,  4.28it/s]
 71%|███████   | 22/31 [00:05<00:02,  4.47it/s]
 74%|███████▍  | 23/31 [00:05<00:01,  5.04it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  5.09it/s]
 81%|████████  | 25/31 [00:05<00:01,  5.00it/s]
 84%|████████▍ | 26/31 [00:05<00:01,  4.93it/s]
 87%|████████▋ | 27/31 [00:06<00:01,  3.96it/s]
 90%|█████████ | 28/31 [00:06<00:00,  3.52it/s]
 94%|█████████▎| 29/31 [00:06<00:00,  3.90it/s]
 97%|█████████▋| 30/31 [00:07<00:00,  4.20it/s]
100%|██████████| 31/31 [00:07<00:00,  4.29it/s]
 25%|██▌       | 3/12 [00:22<01:06,  7.42s/it]
  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:05,  5.05it/s]
  6%|▋         | 2/31 [00:00<00:05,  5.01it/s]
 10%|▉         | 3/31 [00:00<00:04,  5.71it/s]
 13%|█▎        | 4/31 [00:00<00:05,  5.33it/s]
 16%|█▌        | 5/31 [00:00<00:05,  5.12it/s]
 19%|█▉        | 6/31 [00:01<00:04,  5.81it/s]
 23%|██▎       | 7/31 [00:01<00:04,  5.42it/s]
 26%|██▌       | 8/31 [00:01<00:05,  4.09it/s]
 29%|██▉       | 9/31 [00:01<00:05,  4.38it/s]
 32%|███▏      | 10/31 [00:02<00:04,  4.58it/s]
 35%|███▌      | 11/31 [00:02<00:05,  3.80it/s]
 39%|███▊      | 12/31 [00:02<00:04,  4.03it/s]
 42%|████▏     | 13/31 [00:02<00:04,  4.25it/s]
 45%|████▌     | 14/31 [00:03<00:04,  3.65it/s]
 48%|████▊     | 15/31 [00:03<00:04,  3.97it/s]
 52%|█████▏    | 16/31 [00:03<00:04,  3.30it/s]
 55%|█████▍    | 17/31 [00:04<00:04,  3.12it/s]
 58%|█████▊    | 18/31 [00:04<00:03,  3.49it/s]
 61%|██████▏   | 19/31 [00:04<00:03,  3.87it/s]
 65%|██████▍   | 20/31 [00:04<00:03,  3.46it/s]
 68%|██████▊   | 21/31 [00:05<00:02,  3.80it/s]
 71%|███████   | 22/31 [00:05<00:02,  4.10it/s]
 74%|███████▍  | 23/31 [00:05<00:02,  3.54it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  3.88it/s]
 81%|████████  | 25/31 [00:06<00:01,  4.15it/s]
 84%|████████▍ | 26/31 [00:06<00:01,  3.95it/s]
 87%|████████▋ | 27/31 [00:06<00:00,  4.21it/s]
 90%|█████████ | 28/31 [00:06<00:00,  4.37it/s]
 94%|█████████▎| 29/31 [00:07<00:00,  4.44it/s]
 97%|█████████▋| 30/31 [00:07<00:00,  4.56it/s]
100%|██████████| 31/31 [00:07<00:00,  4.17it/s]
 33%|███▎      | 4/12 [00:29<00:59,  7.43s/it]

⚠️ No data available for 4-31. Skipping.

  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:06,  4.74it/s]
  6%|▋         | 2/31 [00:00<00:05,  4.85it/s]
 10%|▉         | 3/31 [00:00<00:08,  3.49it/s]
 13%|█▎        | 4/31 [00:01<00:07,  3.84it/s]
 16%|█▌        | 5/31 [00:01<00:07,  3.47it/s]
 19%|█▉        | 6/31 [00:01<00:07,  3.50it/s]
 23%|██▎       | 7/31 [00:01<00:06,  3.82it/s]
 26%|██▌       | 8/31 [00:02<00:05,  4.09it/s]
 29%|██▉       | 9/31 [00:02<00:04,  4.67it/s]
 32%|███▏      | 10/31 [00:02<00:04,  4.75it/s]
 35%|███▌      | 11/31 [00:02<00:04,  4.76it/s]
 39%|███▊      | 12/31 [00:03<00:05,  3.49it/s]
 42%|████▏     | 13/31 [00:03<00:05,  3.21it/s]
 45%|████▌     | 14/31 [00:03<00:04,  3.56it/s]
 48%|████▊     | 15/31 [00:03<00:04,  3.87it/s]
 52%|█████▏    | 16/31 [00:04<00:04,  3.38it/s]
 55%|█████▍    | 17/31 [00:04<00:03,  3.73it/s]
 58%|█████▊    | 18/31 [00:04<00:03,  4.07it/s]
 61%|██████▏   | 19/31 [00:04<00:02,  4.31it/s]
 65%|██████▍   | 20/31 [00:05<00:02,  4.52it/s]
 68%|██████▊   | 21/31 [00:05<00:02,  4.64it/s]
 71%|███████   | 22/31 [00:05<00:01,  4.77it/s]
 74%|███████▍  | 23/31 [00:05<00:01,  4.80it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  4.87it/s]
 81%|████████  | 25/31 [00:06<00:01,  3.85it/s]
 84%|████████▍ | 26/31 [00:06<00:01,  4.17it/s]
 87%|████████▋ | 27/31 [00:06<00:00,  4.39it/s]
 90%|█████████ | 28/31 [00:06<00:00,  4.51it/s]
 94%|█████████▎| 29/31 [00:07<00:00,  4.65it/s]
 97%|█████████▋| 30/31 [00:07<00:00,  4.77it/s]
100%|██████████| 31/31 [00:07<00:00,  4.17it/s]
 42%|████▏     | 5/12 [00:37<00:52,  7.43s/it]
  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:11,  2.61it/s]
  6%|▋         | 2/31 [00:00<00:08,  3.59it/s]
 10%|▉         | 3/31 [00:00<00:06,  4.17it/s]
 13%|█▎        | 4/31 [00:00<00:05,  4.53it/s]
 16%|█▌        | 5/31 [00:01<00:04,  5.40it/s]
 19%|█▉        | 6/31 [00:01<00:04,  5.30it/s]
 23%|██▎       | 7/31 [00:01<00:04,  5.14it/s]
 26%|██▌       | 8/31 [00:01<00:04,  5.11it/s]
 29%|██▉       | 9/31 [00:01<00:04,  5.11it/s]
 32%|███▏      | 10/31 [00:02<00:05,  4.13it/s]
 35%|███▌      | 11/31 [00:02<00:04,  4.31it/s]
 39%|███▊      | 12/31 [00:02<00:04,  4.45it/s]
 42%|████▏     | 13/31 [00:02<00:03,  4.58it/s]
 45%|████▌     | 14/31 [00:03<00:04,  3.75it/s]
 48%|████▊     | 15/31 [00:03<00:03,  4.08it/s]
 52%|█████▏    | 16/31 [00:03<00:04,  3.56it/s]
 55%|█████▍    | 17/31 [00:03<00:03,  3.91it/s]
 58%|█████▊    | 18/31 [00:04<00:03,  3.46it/s]
 61%|██████▏   | 19/31 [00:04<00:03,  3.80it/s]
 65%|██████▍   | 20/31 [00:04<00:03,  3.63it/s]
 68%|██████▊   | 21/31 [00:05<00:03,  3.26it/s]
 71%|███████   | 22/31 [00:05<00:02,  3.67it/s]
 74%|███████▍  | 23/31 [00:05<00:02,  3.33it/s]
 77%|███████▋  | 24/31 [00:06<00:01,  3.72it/s]
 81%|████████  | 25/31 [00:06<00:01,  3.99it/s]
 84%|████████▍ | 26/31 [00:06<00:01,  4.23it/s]
 87%|████████▋ | 27/31 [00:06<00:01,  3.67it/s]
 90%|█████████ | 28/31 [00:06<00:00,  4.01it/s]
 94%|█████████▎| 29/31 [00:07<00:00,  3.45it/s]
 97%|█████████▋| 30/31 [00:07<00:00,  3.79it/s]
100%|██████████| 31/31 [00:07<00:00,  3.99it/s]
 50%|█████     | 6/12 [00:44<00:45,  7.55s/it]

⚠️ No data available for 6-31. Skipping.

  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:09,  3.26it/s]
  6%|▋         | 2/31 [00:00<00:10,  2.87it/s]
 10%|▉         | 3/31 [00:01<00:10,  2.76it/s]
 13%|█▎        | 4/31 [00:01<00:07,  3.38it/s]
 16%|█▌        | 5/31 [00:01<00:06,  3.78it/s]
 19%|█▉        | 6/31 [00:01<00:06,  4.16it/s]
 23%|██▎       | 7/31 [00:02<00:06,  3.54it/s]
 26%|██▌       | 8/31 [00:02<00:05,  3.92it/s]
 29%|██▉       | 9/31 [00:02<00:05,  4.17it/s]
 32%|███▏      | 10/31 [00:02<00:05,  3.62it/s]
 35%|███▌      | 11/31 [00:02<00:05,  3.97it/s]
 39%|███▊      | 12/31 [00:03<00:04,  4.26it/s]
 42%|████▏     | 13/31 [00:03<00:04,  4.40it/s]
 45%|████▌     | 14/31 [00:03<00:03,  4.51it/s]
 48%|████▊     | 15/31 [00:04<00:04,  3.41it/s]
 52%|█████▏    | 16/31 [00:04<00:03,  3.79it/s]
 55%|█████▍    | 17/31 [00:04<00:03,  4.02it/s]
 58%|█████▊    | 18/31 [00:04<00:03,  4.31it/s]
 61%|██████▏   | 19/31 [00:04<00:02,  4.57it/s]
 65%|██████▍   | 20/31 [00:05<00:02,  4.63it/s]
 68%|██████▊   | 21/31 [00:05<00:01,  5.19it/s]
 71%|███████   | 22/31 [00:05<00:01,  5.07it/s]
 74%|███████▍  | 23/31 [00:05<00:01,  4.93it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  4.97it/s]
 81%|████████  | 25/31 [00:06<00:01,  4.92it/s]
 84%|████████▍ | 26/31 [00:06<00:01,  4.86it/s]
 87%|████████▋ | 27/31 [00:06<00:00,  4.39it/s]
 90%|█████████ | 28/31 [00:06<00:00,  4.60it/s]
 94%|█████████▎| 29/31 [00:06<00:00,  4.73it/s]
 97%|█████████▋| 30/31 [00:07<00:00,  4.81it/s]
100%|██████████| 31/31 [00:07<00:00,  4.24it/s]
 58%|█████▊    | 7/12 [00:52<00:37,  7.47s/it]
  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:11,  2.66it/s]
  6%|▋         | 2/31 [00:00<00:07,  3.69it/s]
 10%|▉         | 3/31 [00:00<00:06,  4.19it/s]
 13%|█▎        | 4/31 [00:00<00:06,  4.50it/s]
 16%|█▌        | 5/31 [00:01<00:07,  3.26it/s]
 19%|█▉        | 6/31 [00:01<00:06,  3.97it/s]
 23%|██▎       | 7/31 [00:01<00:05,  4.22it/s]
 26%|██▌       | 8/31 [00:01<00:05,  4.46it/s]
 29%|██▉       | 9/31 [00:02<00:04,  4.53it/s]
 32%|███▏      | 10/31 [00:02<00:04,  4.73it/s]
 35%|███▌      | 11/31 [00:02<00:04,  4.87it/s]
 39%|███▊      | 12/31 [00:02<00:04,  3.94it/s]
 42%|████▏     | 13/31 [00:03<00:05,  3.52it/s]
 45%|████▌     | 14/31 [00:03<00:04,  3.88it/s]
 48%|████▊     | 15/31 [00:03<00:03,  4.18it/s]
 52%|█████▏    | 16/31 [00:03<00:03,  4.43it/s]
 55%|█████▍    | 17/31 [00:04<00:03,  4.61it/s]
 58%|█████▊    | 18/31 [00:04<00:03,  3.45it/s]
 61%|██████▏   | 19/31 [00:04<00:03,  3.22it/s]
 65%|██████▍   | 20/31 [00:05<00:03,  3.62it/s]
 68%|██████▊   | 21/31 [00:05<00:02,  3.95it/s]
 71%|███████   | 22/31 [00:05<00:02,  4.25it/s]
 74%|███████▍  | 23/31 [00:05<00:01,  4.46it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  4.67it/s]
 81%|████████  | 25/31 [00:06<00:01,  4.78it/s]
 84%|████████▍ | 26/31 [00:06<00:00,  5.35it/s]
 87%|████████▋ | 27/31 [00:06<00:00,  5.17it/s]
 90%|█████████ | 28/31 [00:06<00:00,  5.05it/s]
 94%|█████████▎| 29/31 [00:06<00:00,  4.01it/s]
 97%|█████████▋| 30/31 [00:07<00:00,  4.23it/s]
100%|██████████| 31/31 [00:07<00:00,  4.18it/s]
 67%|██████▋   | 8/12 [00:59<00:29,  7.46s/it]
  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:04,  7.47it/s]
  6%|▋         | 2/31 [00:00<00:05,  5.75it/s]
 10%|▉         | 3/31 [00:00<00:05,  5.33it/s]
 13%|█▎        | 4/31 [00:00<00:05,  5.32it/s]
 16%|█▌        | 5/31 [00:00<00:04,  5.64it/s]
 19%|█▉        | 6/31 [00:01<00:04,  5.42it/s]
 23%|██▎       | 7/31 [00:01<00:04,  5.29it/s]
 26%|██▌       | 8/31 [00:01<00:05,  4.05it/s]
 29%|██▉       | 9/31 [00:01<00:05,  4.28it/s]
 32%|███▏      | 10/31 [00:02<00:04,  4.46it/s]
 35%|███▌      | 11/31 [00:02<00:05,  3.75it/s]
 39%|███▊      | 12/31 [00:02<00:04,  4.07it/s]
 42%|████▏     | 13/31 [00:03<00:05,  3.21it/s]
 45%|████▌     | 14/31 [00:03<00:05,  3.07it/s]
 48%|████▊     | 15/31 [00:03<00:05,  2.97it/s]
 52%|█████▏    | 16/31 [00:03<00:04,  3.41it/s]
 55%|█████▍    | 17/31 [00:04<00:03,  3.81it/s]
 58%|█████▊    | 18/31 [00:04<00:03,  4.09it/s]
 61%|██████▏   | 19/31 [00:04<00:02,  4.20it/s]
 65%|██████▍   | 20/31 [00:04<00:02,  4.29it/s]
 68%|██████▊   | 21/31 [00:05<00:02,  4.43it/s]
 71%|███████   | 22/31 [00:05<00:02,  4.02it/s]
 74%|███████▍  | 23/31 [00:05<00:01,  4.30it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  4.35it/s]
 81%|████████  | 25/31 [00:06<00:01,  4.09it/s]
 84%|████████▍ | 26/31 [00:06<00:01,  3.49it/s]
 87%|████████▋ | 27/31 [00:06<00:01,  3.85it/s]
 90%|█████████ | 28/31 [00:06<00:00,  4.13it/s]
 94%|█████████▎| 29/31 [00:07<00:00,  4.32it/s]
 97%|█████████▋| 30/31 [00:07<00:00,  4.46it/s]
100%|██████████| 31/31 [00:07<00:00,  4.17it/s]
 75%|███████▌  | 9/12 [01:07<00:22,  7.45s/it]

⚠️ No data available for 9-31. Skipping.

  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:06,  4.79it/s]
  6%|▋         | 2/31 [00:00<00:05,  4.85it/s]
 10%|▉         | 3/31 [00:00<00:05,  5.01it/s]
 13%|█▎        | 4/31 [00:00<00:05,  4.94it/s]
 16%|█▌        | 5/31 [00:01<00:05,  4.87it/s]
 19%|█▉        | 6/31 [00:01<00:05,  4.96it/s]
 23%|██▎       | 7/31 [00:01<00:04,  4.95it/s]
 26%|██▌       | 8/31 [00:01<00:04,  5.02it/s]
 29%|██▉       | 9/31 [00:01<00:05,  4.02it/s]
 32%|███▏      | 10/31 [00:02<00:04,  4.25it/s]
 35%|███▌      | 11/31 [00:02<00:04,  4.52it/s]
 39%|███▊      | 12/31 [00:02<00:04,  4.64it/s]
 42%|████▏     | 13/31 [00:02<00:04,  3.84it/s]
 45%|████▌     | 14/31 [00:03<00:04,  4.19it/s]
 48%|████▊     | 15/31 [00:03<00:03,  4.85it/s]
 52%|█████▏    | 16/31 [00:03<00:03,  4.36it/s]
 55%|█████▍    | 17/31 [00:03<00:03,  4.57it/s]
 58%|█████▊    | 18/31 [00:03<00:02,  4.72it/s]
 61%|██████▏   | 19/31 [00:04<00:02,  4.78it/s]
 65%|██████▍   | 20/31 [00:04<00:02,  4.87it/s]
 68%|██████▊   | 21/31 [00:04<00:02,  4.85it/s]
 71%|███████   | 22/31 [00:04<00:01,  4.87it/s]
 74%|███████▍  | 23/31 [00:04<00:01,  5.39it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  5.26it/s]
 81%|████████  | 25/31 [00:05<00:01,  3.94it/s]
 84%|████████▍ | 26/31 [00:05<00:01,  4.14it/s]
 87%|████████▋ | 27/31 [00:05<00:00,  4.36it/s]
 90%|█████████ | 28/31 [00:06<00:00,  4.49it/s]
 94%|█████████▎| 29/31 [00:06<00:00,  4.65it/s]
 97%|█████████▋| 30/31 [00:06<00:00,  3.81it/s]
100%|██████████| 31/31 [00:06<00:00,  4.51it/s]
 83%|████████▎ | 10/12 [01:13<00:14,  7.28s/it]
  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:06,  4.75it/s]
  6%|▋         | 2/31 [00:00<00:06,  4.52it/s]
 10%|▉         | 3/31 [00:00<00:05,  4.88it/s]
 13%|█▎        | 4/31 [00:00<00:05,  4.98it/s]
 16%|█▌        | 5/31 [00:01<00:05,  4.89it/s]
 19%|█▉        | 6/31 [00:01<00:05,  4.96it/s]
 23%|██▎       | 7/31 [00:01<00:05,  4.35it/s]
 26%|██▌       | 8/31 [00:01<00:05,  4.60it/s]
 29%|██▉       | 9/31 [00:01<00:04,  5.25it/s]
 32%|███▏      | 10/31 [00:02<00:04,  5.09it/s]
 35%|███▌      | 11/31 [00:02<00:03,  5.07it/s]
 39%|███▊      | 12/31 [00:02<00:03,  5.02it/s]
 42%|████▏     | 13/31 [00:02<00:03,  4.91it/s]
 45%|████▌     | 14/31 [00:02<00:03,  5.02it/s]
 48%|████▊     | 15/31 [00:03<00:03,  4.98it/s]
 52%|█████▏    | 16/31 [00:03<00:02,  5.01it/s]
 55%|█████▍    | 17/31 [00:03<00:03,  4.49it/s]
 58%|█████▊    | 18/31 [00:03<00:02,  4.63it/s]
 61%|██████▏   | 19/31 [00:03<00:02,  4.74it/s]
 65%|██████▍   | 20/31 [00:04<00:02,  3.81it/s]
 68%|██████▊   | 21/31 [00:04<00:02,  4.06it/s]
 71%|███████   | 22/31 [00:04<00:02,  4.23it/s]
 74%|███████▍  | 23/31 [00:04<00:01,  4.40it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  4.52it/s]
 81%|████████  | 25/31 [00:05<00:01,  4.49it/s]
 84%|████████▍ | 26/31 [00:05<00:00,  5.06it/s]
 87%|████████▋ | 27/31 [00:05<00:00,  5.51it/s]
 90%|█████████ | 28/31 [00:05<00:00,  5.30it/s]
 94%|█████████▎| 29/31 [00:05<00:00,  5.78it/s]
 97%|█████████▋| 30/31 [00:06<00:00,  5.54it/s]
100%|██████████| 31/31 [00:06<00:00,  4.84it/s]
 92%|█████████▏| 11/12 [01:20<00:07,  7.01s/it]

⚠️ No data available for 11-31. Skipping.

  0%|          | 0/31 [00:00<?, ?it/s]
  3%|▎         | 1/31 [00:00<00:06,  4.72it/s]
  6%|▋         | 2/31 [00:00<00:04,  5.88it/s]
 10%|▉         | 3/31 [00:00<00:05,  5.34it/s]
 13%|█▎        | 4/31 [00:00<00:05,  4.97it/s]
 16%|█▌        | 5/31 [00:01<00:07,  3.31it/s]
 19%|█▉        | 6/31 [00:01<00:06,  3.78it/s]
 23%|██▎       | 7/31 [00:01<00:05,  4.09it/s]
 26%|██▌       | 8/31 [00:01<00:05,  4.32it/s]
 29%|██▉       | 9/31 [00:02<00:05,  4.32it/s]
 32%|███▏      | 10/31 [00:02<00:04,  4.50it/s]
 35%|███▌      | 11/31 [00:02<00:04,  4.61it/s]
 39%|███▊      | 12/31 [00:02<00:05,  3.79it/s]
 42%|████▏     | 13/31 [00:03<00:04,  4.07it/s]
 45%|████▌     | 14/31 [00:03<00:03,  4.69it/s]
 48%|████▊     | 15/31 [00:03<00:04,  3.86it/s]
 52%|█████▏    | 16/31 [00:03<00:03,  4.13it/s]
 55%|█████▍    | 17/31 [00:03<00:03,  4.28it/s]
 58%|█████▊    | 18/31 [00:04<00:02,  4.52it/s]
 61%|██████▏   | 19/31 [00:04<00:02,  4.52it/s]
 65%|██████▍   | 20/31 [00:04<00:02,  4.56it/s]
 68%|██████▊   | 21/31 [00:04<00:02,  4.53it/s]
 71%|███████   | 22/31 [00:05<00:01,  4.62it/s]
 74%|███████▍  | 23/31 [00:05<00:01,  4.67it/s]
 77%|███████▋  | 24/31 [00:05<00:01,  4.72it/s]
 81%|████████  | 25/31 [00:05<00:01,  4.80it/s]
 84%|████████▍ | 26/31 [00:05<00:01,  4.87it/s]
 87%|████████▋ | 27/31 [00:06<00:01,  3.87it/s]
 90%|█████████ | 28/31 [00:06<00:00,  4.40it/s]
 94%|█████████▎| 29/31 [00:06<00:00,  4.52it/s]
 97%|█████████▋| 30/31 [00:06<00:00,  4.24it/s]
100%|██████████| 31/31 [00:07<00:00,  4.27it/s]
100%|██████████| 12/12 [01:27<00:00,  7.30s/it]

In [26]:
df_final

,Time,Icon,Temperature,Condition,Wind,Wind Direction,Humidity,Pressure,Visibility,day,month
0,"00:51Mon, 1 Jan",,6 °C,Mostly cloudy.,11 km/h,↑,55%,1016 mbar,16 km,1,1
1,01:51,,6 °C,Overcast.,7 km/h,↑,57%,1016 mbar,16 km,1,1
2,02:51,,5 °C,Overcast.,No wind,↑,60%,1016 mbar,16 km,1,1
3,03:51,,5 °C,Overcast.,6 km/h,↑,62%,1015 mbar,16 km,1,1
4,04:51,,4 °C,Partly cloudy.,No wind,↑,68%,1015 mbar,16 km,1,1
...,...,...,...,...,...,...,...,...,...,...,...
9649,20:51,,7 °C,Rain. Fog.,6 km/h,↑,86%,1003 mbar,6 km,31,12
9650,21:56,,7 °C,Heavy rain. Fog.,7 km/h,↑,89%,1003 mbar,2 km,31,12
9651,22:33,,7 °C,Rain. Fog.,9 km/h,↑,90%,1002 mbar,3 km,31,12
9652,22:51,,7 °C,Rain. Fog.,19 km/h,↑,93%,1000 mbar,8 km,31,12
9653,23:51,,8 °C,Mostly cloudy.,15 km/h,↑,89%,999 mbar,13 km,31,12

In [27]:
df_final["year"] = 2024
df_final["Time_clean"] = df_final["Time"].str.extract(r"(\d{2}:\d{2})")
df_final["Timestamp"] = pd.to_datetime(
    df_final["year"].astype(str) + "-" +
    df_final["month"].astype(str) + "-" +
    df_final["day"].astype(str) + " " +
    df_final["Time_clean"],
    format="%Y-%m-%d %H:%M"
)
df_final.drop(columns=["Time_clean"], inplace=True)

In [28]:
df_final

,Time,Icon,Temperature,Condition,Wind,Wind Direction,Humidity,Pressure,Visibility,day,month,year,Timestamp
0,"00:51Mon, 1 Jan",,6 °C,Mostly cloudy.,11 km/h,↑,55%,1016 mbar,16 km,1,1,2024,2024-01-01 00:51:00
1,01:51,,6 °C,Overcast.,7 km/h,↑,57%,1016 mbar,16 km,1,1,2024,2024-01-01 01:51:00
2,02:51,,5 °C,Overcast.,No wind,↑,60%,1016 mbar,16 km,1,1,2024,2024-01-01 02:51:00
3,03:51,,5 °C,Overcast.,6 km/h,↑,62%,1015 mbar,16 km,1,1,2024,2024-01-01 03:51:00
4,04:51,,4 °C,Partly cloudy.,No wind,↑,68%,1015 mbar,16 km,1,1,2024,2024-01-01 04:51:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9649,20:51,,7 °C,Rain. Fog.,6 km/h,↑,86%,1003 mbar,6 km,31,12,2024,2024-12-31 20:51:00
9650,21:56,,7 °C,Heavy rain. Fog.,7 km/h,↑,89%,1003 mbar,2 km,31,12,2024,2024-12-31 21:56:00
9651,22:33,,7 °C,Rain. Fog.,9 km/h,↑,90%,1002 mbar,3 km,31,12,2024,2024-12-31 22:33:00
9652,22:51,,7 °C,Rain. Fog.,19 km/h,↑,93%,1000 mbar,8 km,31,12,2024,2024-12-31 22:51:00
9653,23:51,,8 °C,Mostly cloudy.,15 km/h,↑,89%,999 mbar,13 km,31,12,2024,2024-12-31 23:51:00

In [29]:
df_final["Timestamp"] = (
    pd.to_datetime(df_final["Timestamp"], format="%Y-%m-%d %H:%M")
      .dt.round("30min")
      .dt.strftime("%Y-%m-%d %H:%M")
)
df_final

,Time,Icon,Temperature,Condition,Wind,Wind Direction,Humidity,Pressure,Visibility,day,month,year,Timestamp
0,"00:51Mon, 1 Jan",,6 °C,Mostly cloudy.,11 km/h,↑,55%,1016 mbar,16 km,1,1,2024,2024-01-01 01:00
1,01:51,,6 °C,Overcast.,7 km/h,↑,57%,1016 mbar,16 km,1,1,2024,2024-01-01 02:00
2,02:51,,5 °C,Overcast.,No wind,↑,60%,1016 mbar,16 km,1,1,2024,2024-01-01 03:00
3,03:51,,5 °C,Overcast.,6 km/h,↑,62%,1015 mbar,16 km,1,1,2024,2024-01-01 04:00
4,04:51,,4 °C,Partly cloudy.,No wind,↑,68%,1015 mbar,16 km,1,1,2024,2024-01-01 05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9649,20:51,,7 °C,Rain. Fog.,6 km/h,↑,86%,1003 mbar,6 km,31,12,2024,2024-12-31 21:00
9650,21:56,,7 °C,Heavy rain. Fog.,7 km/h,↑,89%,1003 mbar,2 km,31,12,2024,2024-12-31 22:00
9651,22:33,,7 °C,Rain. Fog.,9 km/h,↑,90%,1002 mbar,3 km,31,12,2024,2024-12-31 22:30
9652,22:51,,7 °C,Rain. Fog.,19 km/h,↑,93%,1000 mbar,8 km,31,12,2024,2024-12-31 23:00
9653,23:51,,8 °C,Mostly cloudy.,15 km/h,↑,89%,999 mbar,13 km,31,12,2024,2025-01-01 00:00

In [30]:
df_final = df_final.drop(['Icon', 'Wind Direction', 'Time', 'day', 'month', 'year'], axis=1)

In [31]:
df_final

,Temperature,Condition,Wind,Humidity,Pressure,Visibility,Timestamp
0,6 °C,Mostly cloudy.,11 km/h,55%,1016 mbar,16 km,2024-01-01 01:00
1,6 °C,Overcast.,7 km/h,57%,1016 mbar,16 km,2024-01-01 02:00
2,5 °C,Overcast.,No wind,60%,1016 mbar,16 km,2024-01-01 03:00
3,5 °C,Overcast.,6 km/h,62%,1015 mbar,16 km,2024-01-01 04:00
4,4 °C,Partly cloudy.,No wind,68%,1015 mbar,16 km,2024-01-01 05:00
...,...,...,...,...,...,...,...
9649,7 °C,Rain. Fog.,6 km/h,86%,1003 mbar,6 km,2024-12-31 21:00
9650,7 °C,Heavy rain. Fog.,7 km/h,89%,1003 mbar,2 km,2024-12-31 22:00
9651,7 °C,Rain. Fog.,9 km/h,90%,1002 mbar,3 km,2024-12-31 22:30
9652,7 °C,Rain. Fog.,19 km/h,93%,1000 mbar,8 km,2024-12-31 23:00
9653,8 °C,Mostly cloudy.,15 km/h,89%,999 mbar,13 km,2025-01-01 00:00

In [32]:
df_final.to_csv('weather_data2024.csv', index=False)